//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty.Resource.Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageTitleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageTitleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beauty.Resource.Presentation.PageTitleResource", typeof(PageTitleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت دهی.
        /// </summary>
        public static string AppointmentIndex {
            get {
                return ResourceManager.GetString("AppointmentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت مشتریان.
        /// </summary>
        public static string CustomerIndex {
            get {
                return ResourceManager.GetString("CustomerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات مشتری.
        /// </summary>
        public static string CustomerModify {
            get {
                return ResourceManager.GetString("CustomerModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشخوان.
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت لاین.
        /// </summary>
        public static string LineIndex {
            get {
                return ResourceManager.GetString("LineIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش سطح دسترسی.
        /// </summary>
        public static string PermissionIndex {
            get {
                return ResourceManager.GetString("PermissionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  مدیریت پرسنل.
        /// </summary>
        public static string PersonnelIndex {
            get {
                return ResourceManager.GetString("PersonnelIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات پرسنل.
        /// </summary>
        public static string PersonnelModify {
            get {
                return ResourceManager.GetString("PersonnelModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کالا.
        /// </summary>
        public static string ProductIndex {
            get {
                return ResourceManager.GetString("ProductIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کالا.
        /// </summary>
        public static string ProductModify {
            get {
                return ResourceManager.GetString("ProductModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت خدمات.
        /// </summary>
        public static string ServiceIndex {
            get {
                return ResourceManager.GetString("ServiceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پکیج خدمت.
        /// </summary>
        public static string ServicePackage {
            get {
                return ResourceManager.GetString("ServicePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد پکیج خدمات.
        /// </summary>
        public static string ServicePackageCreate {
            get {
                return ResourceManager.GetString("ServicePackageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پکیج خدمات.
        /// </summary>
        public static string ServicePackageUpdate {
            get {
                return ResourceManager.GetString("ServicePackageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت پیامک.
        /// </summary>
        public static string SmsIndex {
            get {
                return ResourceManager.GetString("SmsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پیامک.
        /// </summary>
        public static string SmsModify {
            get {
                return ResourceManager.GetString("SmsModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت حساب.
        /// </summary>
        public static string UserIndex {
            get {
                return ResourceManager.GetString("UserIndex", resourceCulture);
            }
        }
    }
}
