//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayResource_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResource_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beauty.Resource.DisplayResource-fa", typeof(DisplayResource_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات بعد از ارسال.
        /// </summary>
        public static string AfterHours {
            get {
                return ResourceManager.GetString("AfterHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ مراجعه.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش پرداخت نوبت.
        /// </summary>
        public static string AppointmentPrePayment {
            get {
                return ResourceManager.GetString("AppointmentPrePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد پیش پرداخت نوبت.
        /// </summary>
        public static string AppointmentPrePaymentPerecnt {
            get {
                return ResourceManager.GetString("AppointmentPrePaymentPerecnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ارسال پیامک یاداوری نوبت.
        /// </summary>
        public static string AppointmentRemindingSmsSendTime {
            get {
                return ResourceManager.GetString("AppointmentRemindingSmsSendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان مراجعه.
        /// </summary>
        public static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر پروفایل.
        /// </summary>
        public static string AvatarFile {
            get {
                return ResourceManager.GetString("AvatarFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات قبل از ارسال.
        /// </summary>
        public static string BeforeHours {
            get {
                return ResourceManager.GetString("BeforeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت پایان کار سالن.
        /// </summary>
        public static string ClosingTime {
            get {
                return ResourceManager.GetString("ClosingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمزعبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع همکاری.
        /// </summary>
        public static string CooperationType {
            get {
                return ResourceManager.GetString("CooperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فعلی.
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری اجباری می باشد.
        /// </summary>
        public static string CustomerProfile {
            get {
                return ResourceManager.GetString("CustomerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد پیش فرض خدمت-پرسنل.
        /// </summary>
        public static string DefaultPersonnelServicePerecnt {
            get {
                return ResourceManager.GetString("DefaultPersonnelServicePerecnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تخفیف.
        /// </summary>
        public static string DiscountPrice {
            get {
                return ResourceManager.GetString("DiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار زمان به دقیقه.
        /// </summary>
        public static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال تاسیس.
        /// </summary>
        public static string EstablishYear {
            get {
                return ResourceManager.GetString("EstablishYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از ساعت.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال/غیرفعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان همکاری.
        /// </summary>
        public static string JobEnd {
            get {
                return ResourceManager.GetString("JobEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع همکاری.
        /// </summary>
        public static string JobStart {
            get {
                return ResourceManager.GetString("JobStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاین.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت شروع کار سالن.
        /// </summary>
        public static string OpeningTime {
            get {
                return ResourceManager.GetString("OpeningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ به ازای هر ساعت اضافه کاری پرسنل حقوقی.
        /// </summary>
        public static string OvertimePay {
            get {
                return ResourceManager.GetString("OvertimePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنل.
        /// </summary>
        public static string PersonnelCode {
            get {
                return ResourceManager.GetString("PersonnelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد بازاریابی پرسنل برای پرسنل.
        /// </summary>
        public static string PersonnelToPersonnelSalePerecnt {
            get {
                return ResourceManager.GetString("PersonnelToPersonnelSalePerecnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش پرداخت.
        /// </summary>
        public static string Prepayment {
            get {
                return ResourceManager.GetString("Prepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت (تومان).
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار؟.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربری.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان حقوق ماهیانه.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره سالن.
        /// </summary>
        public static string SalonAbout {
            get {
                return ResourceManager.GetString("SalonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد انجام برای یکبار رایگان شدن.
        /// </summary>
        public static string TakeItFreeCount {
            get {
                return ResourceManager.GetString("TakeItFreeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا ساعت.
        /// </summary>
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
