//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagingResource_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagingResource_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beauty.Resource.MessagingResource-fa", typeof(MessagingResource_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف با موفقیت برای نوبت ثبت شد.
        /// </summary>
        public static string AppoinmentAddDiscountSucceed {
            get {
                return ResourceManager.GetString("AppoinmentAddDiscountSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت مبلغ نوبت با موفقیت ثبت شد.
        /// </summary>
        public static string AppoinmentAddPaymentSucceed {
            get {
                return ResourceManager.GetString("AppoinmentAddPaymentSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت با موفقیت کنسل شد.
        /// </summary>
        public static string AppoinmentCancelSucceed {
            get {
                return ResourceManager.GetString("AppoinmentCancelSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت با موفقیت ثبت شد.
        /// </summary>
        public static string AppoinmentCreateSucceed {
            get {
                return ResourceManager.GetString("AppoinmentCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف نوبت با موفقیت حذف شد.
        /// </summary>
        public static string AppoinmentDeleteDiscountSucceed {
            get {
                return ResourceManager.GetString("AppoinmentDeleteDiscountSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف پرداخت با موفقیت انجام شد.
        /// </summary>
        public static string AppoinmentDeletePaymentSucceed {
            get {
                return ResourceManager.GetString("AppoinmentDeletePaymentSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت با موفقیت حذف شد.
        /// </summary>
        public static string AppoinmentDeleteSucceed {
            get {
                return ResourceManager.GetString("AppoinmentDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت انجام شد.
        /// </summary>
        public static string AppoinmentDoneSucceed {
            get {
                return ResourceManager.GetString("AppoinmentDoneSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت بعلت وجود خدمت انجام  شده قابل لغو شدن نیست.
        /// </summary>
        public static string AppoinmentNotCancel {
            get {
                return ResourceManager.GetString("AppoinmentNotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت بعلت وجود خدمت انجام شده یا کنسل شده قابل حذف نیست.
        /// </summary>
        public static string AppoinmentNotDelete {
            get {
                return ResourceManager.GetString("AppoinmentNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع پرداختی ها نمیتواند بزرگتر از مبلغ کل نوبت باشد.
        /// </summary>
        public static string AppoinmentPaymentSumCanNotBeGreaterThanTotalPrice {
            get {
                return ResourceManager.GetString("AppoinmentPaymentSumCanNotBeGreaterThanTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت از نوبت با موفقیت حذف شد.
        /// </summary>
        public static string AppoinmentServiceDeleteSucceed {
            get {
                return ResourceManager.GetString("AppoinmentServiceDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت با موفقیت ویرایش شد.
        /// </summary>
        public static string AppoinmentUpdateSucceed {
            get {
                return ResourceManager.GetString("AppoinmentUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب تاریخ نوبت اجباری می باشد.
        /// </summary>
        public static string AppointmentDateIsRequierd {
            get {
                return ResourceManager.GetString("AppointmentDateIsRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ مراجعه نوبت باید بزرگتر از تاریخ امروز باشد.
        /// </summary>
        public static string AppointmentDateMustBeGreaterThanNow {
            get {
                return ResourceManager.GetString("AppointmentDateMustBeGreaterThanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت با این مشتری و تاریخ قبلا ثبت شده.
        /// </summary>
        public static string AppointmentExistByCustomerAndDate {
            get {
                return ResourceManager.GetString("AppointmentExistByCustomerAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت یافت نشد.
        /// </summary>
        public static string AppointmentNotExist {
            get {
                return ResourceManager.GetString("AppointmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبتی برای این مشتری در تاریخ انتخاب شده یافت نشد.
        /// </summary>
        public static string AppointmentNotExistByCustomerAndDate {
            get {
                return ResourceManager.GetString("AppointmentNotExistByCustomerAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت نوبت یافت نشد.
        /// </summary>
        public static string AppointmentPaymentNotExist {
            get {
                return ResourceManager.GetString("AppointmentPaymentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرهزینه های خدمت با موفقیت ثبت شد.
        /// </summary>
        public static string AppointmentServiceDetailsCreateSucceed {
            get {
                return ResourceManager.GetString("AppointmentServiceDetailsCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریزهزینه های خدمت یافت نشد.
        /// </summary>
        public static string AppointmentServiceDetailsNotExist {
            get {
                return ResourceManager.GetString("AppointmentServiceDetailsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت قبلا انجام شده.
        /// </summary>
        public static string AppointmentServiceDoneNotFound {
            get {
                return ResourceManager.GetString("AppointmentServiceDoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت نوبت انجام شد.
        /// </summary>
        public static string AppointmentServiceDoneSucceed {
            get {
                return ResourceManager.GetString("AppointmentServiceDoneSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت نوبت تکراری ثبت شده.
        /// </summary>
        public static string AppointmentServiceDuplicates {
            get {
                return ResourceManager.GetString("AppointmentServiceDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت تکراری: این خدمت به نوبت مشتری قبلا اضافه شده.
        /// </summary>
        public static string AppointmentServiceExistForCustomer {
            get {
                return ResourceManager.GetString("AppointmentServiceExistForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب خدمت یا خدمات  نوبت  اجباری می باشد.
        /// </summary>
        public static string AppointmentServiceIsRequired {
            get {
                return ResourceManager.GetString("AppointmentServiceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چکی با این مشخصات به مشتری افزوده شده.
        /// </summary>
        public static string CustomerChequeAlreadyAdded {
            get {
                return ResourceManager.GetString("CustomerChequeAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک با موفقیت به مشتری افزوده شد.
        /// </summary>
        public static string CustomerChequeCreateSucceed {
            get {
                return ResourceManager.GetString("CustomerChequeCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخاطب با موفقیت حذف شد.
        /// </summary>
        public static string CustomerContactDeleteSucceed {
            get {
                return ResourceManager.GetString("CustomerContactDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس برای مشتری دیگری ثبت شده.
        /// </summary>
        public static string CustomerContactExist {
            get {
                return ResourceManager.GetString("CustomerContactExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مشتری با موفقیت ثبت شد.
        /// </summary>
        public static string CustomerCreateSucceed {
            get {
                return ResourceManager.GetString("CustomerCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مشتری انجام نشد.
        /// </summary>
        public static string CustomerDeleteFaild {
            get {
                return ResourceManager.GetString("CustomerDeleteFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مشتری با موفقیت انجام شد.
        /// </summary>
        public static string CustomerDeleteSucceed {
            get {
                return ResourceManager.GetString("CustomerDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری با این مشخصات قبلا ثبت شده میتوانید آنرا ویرایش نمایید.
        /// </summary>
        public static string CustomerExist {
            get {
                return ResourceManager.GetString("CustomerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مشتری اجباری می باشد.
        /// </summary>
        public static string CustomerIsRequierd {
            get {
                return ResourceManager.GetString("CustomerIsRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری با این نام و نام خوانوادگی قبلا ثبت شده میتوانید آنرا ویرایش نمایید.
        /// </summary>
        public static string CustomerNameAndLastName {
            get {
                return ResourceManager.GetString("CustomerNameAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری یافت نشد.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پروفایل انجام نشد.
        /// </summary>
        public static string CustomerUpdateFaild {
            get {
                return ResourceManager.GetString("CustomerUpdateFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مشتری با موفقیت ویرایش شد.
        /// </summary>
        public static string CustomerUpdateSucceed {
            get {
                return ResourceManager.GetString("CustomerUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لاین با موفقیت حذف شد.
        /// </summary>
        public static string LineDeleteSucceed {
            get {
                return ResourceManager.GetString("LineDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاین قبلا ثبت شده.
        /// </summary>
        public static string LineExist {
            get {
                return ResourceManager.GetString("LineExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاین اجباری می باشد.
        /// </summary>
        public static string LineIsRequired {
            get {
                return ResourceManager.GetString("LineIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاین یافت نشد.
        /// </summary>
        public static string LineNotFound {
            get {
                return ResourceManager.GetString("LineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش با موفقیت انجام شد.
        /// </summary>
        public static string LineUpdateSucceed {
            get {
                return ResourceManager.GetString("LineUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقه تغییر داده با موفقیت ثبت شد.
        /// </summary>
        public static string LogDataModificationCreateSucceed {
            get {
                return ResourceManager.GetString("LogDataModificationCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری با موفقیت انجام شد.
        /// </summary>
        public static string LoginSucceed {
            get {
                return ResourceManager.GetString("LoginSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دستگاه موبایل مجاز نصب شده.
        /// </summary>
        public static string MaxDeviceReached {
            get {
                return ResourceManager.GetString("MaxDeviceReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه موبایل:اطلاعات شناسایی دستگاه ارسال نشد.
        /// </summary>
        public static string MobileDeviceNotRecognized {
            get {
                return ResourceManager.GetString("MobileDeviceNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه موبای در برنامه ثبت نشده.
        /// </summary>
        public static string MobileDeviceNotRegisterd {
            get {
                return ResourceManager.GetString("MobileDeviceNotRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل اجباری می باشد.
        /// </summary>
        public static string MobileIsRequired {
            get {
                return ResourceManager.GetString("MobileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل باید 11 رقمی وارد شود.
        /// </summary>
        public static string MobileMustBe11Digits {
            get {
                return ResourceManager.GetString("MobileMustBe11Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری برای استفاده از این برنامه برای شما تعریف نشده .
        /// </summary>
        public static string MobileNotUserInRole {
            get {
                return ResourceManager.GetString("MobileNotUserInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری پرسنل با موفقیت ایجاد شد.
        /// </summary>
        public static string PersonnelAccountCreateSucceed {
            get {
                return ResourceManager.GetString("PersonnelAccountCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری پرسنل با موفقیت ویرایش شد.
        /// </summary>
        public static string PersonnelAccountUpdateSucceed {
            get {
                return ResourceManager.GetString("PersonnelAccountUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخاطب با موفقیت حذف شد.
        /// </summary>
        public static string PersonnelContactDeleteSucceed {
            get {
                return ResourceManager.GetString("PersonnelContactDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس قبلا برای پزسنل دیگری ثبت شده.
        /// </summary>
        public static string PersonnelContactExist {
            get {
                return ResourceManager.GetString("PersonnelContactExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پرسنل با موفقیت ثبت شد.
        /// </summary>
        public static string PersonnelCreateSucceed {
            get {
                return ResourceManager.GetString("PersonnelCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف پرسنل انجام نشد.
        /// </summary>
        public static string PersonnelDeleteFaild {
            get {
                return ResourceManager.GetString("PersonnelDeleteFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف پرسنل با موفقیت انجام شد.
        /// </summary>
        public static string PersonnelDeleteSucceed {
            get {
                return ResourceManager.GetString("PersonnelDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنلی با این مشخصات قبلا ثبت شده میتوانید آنرا ویرایش نمایید.
        /// </summary>
        public static string PersonnelExist {
            get {
                return ResourceManager.GetString("PersonnelExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مالی پرسنل با موفقیت انجام شد.
        /// </summary>
        public static string PersonnelFinancialUpdateSucceed {
            get {
                return ResourceManager.GetString("PersonnelFinancialUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا پروفایل پرسنل را ثبت کنید.
        /// </summary>
        public static string PersonnelMustCreateFirst {
            get {
                return ResourceManager.GetString("PersonnelMustCreateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنلی با این نام و نام خوانوادگی قبلا ثبت شده میتوانید آنرا ویرایش نمایید.
        /// </summary>
        public static string PersonnelNameAndLastName {
            get {
                return ResourceManager.GetString("PersonnelNameAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل یافت نشد.
        /// </summary>
        public static string PersonnelNotFound {
            get {
                return ResourceManager.GetString("PersonnelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت به پرسنل با موفقیت افزوده شد.
        /// </summary>
        public static string PersonnelServiceAddedSuccessfuly {
            get {
                return ResourceManager.GetString("PersonnelServiceAddedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این خدمت در حال حاضر به پرسنل اختصاص داده شده .
        /// </summary>
        public static string PersonnelServiceAlreadyAdded {
            get {
                return ResourceManager.GetString("PersonnelServiceAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت به پرسنل با موفقیت حذف شد.
        /// </summary>
        public static string PersonnelServiceDeletedSuccessfuly {
            get {
                return ResourceManager.GetString("PersonnelServiceDeletedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این خدمت برای پرسنل فعلی ثبت نشده.
        /// </summary>
        public static string PersonnelServiceNotFound {
            get {
                return ResourceManager.GetString("PersonnelServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات پرسنل با موفقیت ویرایش شد.
        /// </summary>
        public static string PersonnelServicesUpdateSucceed {
            get {
                return ResourceManager.GetString("PersonnelServicesUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پروفایل انجام نشد.
        /// </summary>
        public static string PersonnelUpdateFaild {
            get {
                return ResourceManager.GetString("PersonnelUpdateFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش با موفقیت انجام شد.
        /// </summary>
        public static string PersonnelUpdateSucceed {
            get {
                return ResourceManager.GetString("PersonnelUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع و پایان اجباری می باشد.
        /// </summary>
        public static string PersonnelWorkingTimeUpdateFromAndToIsRequired {
            get {
                return ResourceManager.GetString("PersonnelWorkingTimeUpdateFromAndToIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات کاری پرسنل با موفقیت بروزرسانی شد.
        /// </summary>
        public static string PersonnelWorkingTimeUpdateSucceed {
            get {
                return ResourceManager.GetString("PersonnelWorkingTimeUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن اجباری می باشد.
        /// </summary>
        public static string PhoneIsRequired {
            get {
                return ResourceManager.GetString("PhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول با موفقیت ایجاد شد.
        /// </summary>
        public static string ProductCreateSucceed {
            get {
                return ResourceManager.GetString("ProductCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف کالا انجام نشد.
        /// </summary>
        public static string ProductDeleteFaild {
            get {
                return ResourceManager.GetString("ProductDeleteFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا با موفقیت حذف شد.
        /// </summary>
        public static string ProductDeleteSucceed {
            get {
                return ResourceManager.GetString("ProductDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولی با این نام یا کد قبلا ثبت شده.
        /// </summary>
        public static string ProductExist {
            get {
                return ResourceManager.GetString("ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف تصویر کالا انجام نشد.
        /// </summary>
        public static string ProductImageDeleteFaild {
            get {
                return ResourceManager.GetString("ProductImageDeleteFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف تصویر کالا با موفقیت انجام شد.
        /// </summary>
        public static string ProductImageDeleteSucceed {
            get {
                return ResourceManager.GetString("ProductImageDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر کالا یافت نشد.
        /// </summary>
        public static string ProductImageNotFound {
            get {
                return ResourceManager.GetString("ProductImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا یافت نشد.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربری یافت نشد.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستزسی برای شما تعیین نشده.
        /// </summary>
        public static string RolePermissionsNotDefined {
            get {
                return ResourceManager.GetString("RolePermissionsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی نقش بروزرسانی شد.
        /// </summary>
        public static string RolePermissionUpdatedSucceed {
            get {
                return ResourceManager.GetString("RolePermissionUpdatedSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخاطب با موفقیت حذف شد.
        /// </summary>
        public static string SalonContactDeleteSucceed {
            get {
                return ResourceManager.GetString("SalonContactDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات سالن انجام نشد.
        /// </summary>
        public static string SalonInfoUpdateFaild {
            get {
                return ResourceManager.GetString("SalonInfoUpdateFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات سالن با موفقیت برزورسانی شد.
        /// </summary>
        public static string SalonInfoUpdateSucceed {
            get {
                return ResourceManager.GetString("SalonInfoUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت فعال شد.
        /// </summary>
        public static string ServiceActiveSucceed {
            get {
                return ResourceManager.GetString("ServiceActiveSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت جدید با موفقیت ثبت شد.
        /// </summary>
        public static string ServiceCreateSucceed {
            get {
                return ResourceManager.GetString("ServiceCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت غیرفعال شد.
        /// </summary>
        public static string ServiceDeactiveSucceed {
            get {
                return ResourceManager.GetString("ServiceDeactiveSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت با موفقیت حذف شد.
        /// </summary>
        public static string ServiceDeleteSucceed {
            get {
                return ResourceManager.GetString("ServiceDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان سرویس طولانی هست.
        /// </summary>
        public static string ServiceDurationIsLong {
            get {
                return ResourceManager.GetString("ServiceDurationIsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سرویس تکراری وارد شده.
        /// </summary>
        public static string ServiceNameDuplicate {
            get {
                return ResourceManager.GetString("ServiceNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمتی با این عنوان قبلا ثبت شده.
        /// </summary>
        public static string ServiceNameExist {
            get {
                return ResourceManager.GetString("ServiceNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت یافت نشد.
        /// </summary>
        public static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پکیج خدمات با موفقیت ایجاد شد.
        /// </summary>
        public static string ServicePackageCreateSucceed {
            get {
                return ResourceManager.GetString("ServicePackageCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پکیج قابل حذف نیست.
        /// </summary>
        public static string ServicePackageDeleteFaild {
            get {
                return ResourceManager.GetString("ServicePackageDeleteFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت پکیج قابل حذف نیست.
        /// </summary>
        public static string ServicePackageDeleteServiceFaild {
            get {
                return ResourceManager.GetString("ServicePackageDeleteServiceFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف خدمت پکیج با موفقیت انجام شد.
        /// </summary>
        public static string ServicePackageDeleteServiceSucceed {
            get {
                return ResourceManager.GetString("ServicePackageDeleteServiceSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف پکیج با موفقیت انجام شد.
        /// </summary>
        public static string ServicePackageDeleteSucceed {
            get {
                return ResourceManager.GetString("ServicePackageDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف کلی یا تخفیف آیتمی اجباری می باشد.
        /// </summary>
        public static string ServicePackageDiscountIsRequired {
            get {
                return ResourceManager.GetString("ServicePackageDiscountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت نباید تکراری انتخاب شده باشد.
        /// </summary>
        public static string ServicePackageItemDuplicates {
            get {
                return ResourceManager.GetString("ServicePackageItemDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب خدمات پکیج اجباری می باشد.
        /// </summary>
        public static string ServicePackageItemIsRequired {
            get {
                return ResourceManager.GetString("ServicePackageItemIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پکیجی با این عنوان قبلا ثبت شده.
        /// </summary>
        public static string ServicePackageNameExist {
            get {
                return ResourceManager.GetString("ServicePackageNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پکیج خدمات با موفقیت ویرایش شد.
        /// </summary>
        public static string ServicePackageUpdateSucceed {
            get {
                return ResourceManager.GetString("ServicePackageUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت خدمت نباید بیشتر از پیش پرداخت باشد.
        /// </summary>
        public static string ServicePrepaymentIsGreaterThanPrice {
            get {
                return ResourceManager.GetString("ServicePrepaymentIsGreaterThanPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تداخل قیمت و جزییات: خدمت یا باید قیمت داشته باشد یا جزییات.
        /// </summary>
        public static string ServicePriceAndDetailsConflict {
            get {
                return ResourceManager.GetString("ServicePriceAndDetailsConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت خدمت یا جزییات خدمت را وارد کنید.
        /// </summary>
        public static string ServicePriceIsRequired {
            get {
                return ResourceManager.GetString("ServicePriceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش خدمت با موفقیت انجام شد.
        /// </summary>
        public static string ServiceUpdateSucceed {
            get {
                return ResourceManager.GetString("ServiceUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامکی با این عنوان قبلا تعریف شده.
        /// </summary>
        public static string SmsMessageExist {
            get {
                return ResourceManager.GetString("SmsMessageExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک یافت نشد.
        /// </summary>
        public static string SmsMessageNotFound {
            get {
                return ResourceManager.GetString("SmsMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  اطلاعات پیامک با موفقیت ویرایش شد.
        /// </summary>
        public static string SmsMessageUpdateSucceed {
            get {
                return ResourceManager.GetString("SmsMessageUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یا موفقیت ایجاد شد.
        /// </summary>
        public static string UserCreateSucceed {
            get {
                return ResourceManager.GetString("UserCreateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف کاربر با موفقیت انجام شد.
        /// </summary>
        public static string UserDeleteSucceed {
            get {
                return ResourceManager.GetString("UserDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این نام قبلا ثبت شده.
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر غیر فعال می باشد.
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با موفقیت ویرایش شد.
        /// </summary>
        public static string UserUpdateSucceed {
            get {
                return ResourceManager.GetString("UserUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این رمز عبور یافت نشد.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این نام کاربری یافت نشد.
        /// </summary>
        public static string WrongUsername {
            get {
                return ResourceManager.GetString("WrongUsername", resourceCulture);
            }
        }
    }
}
